### ISSUE TITLE
App crashes on Logout

### ISSUE THREAD

**Issue by maximilianweidenauer** [sibvisions/reactUI#146]
In some screens (tested with admin simple screen and features contacts screen), when I try to logout, when those screens are opened, the app crashes. Error: Maximum update depth exceeded error, like on monday 13. 07., could be related to the label again?

**Comment by gimmixAT** [comment]
This should be fixed. The problem was the splitpanel calling a remeasure in an layouteffect although it was hidden. Generally speaking having the style object as a Effect dependency isn't a good idea. We should rather use the width & height explicitly because the style object will always be different.
