### ISSUE TITLE
changedValues support

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#183]
The latest server sends the property

  deletedRow 

for DataProviderChanged responses.

  >= 0 -> specific row number deleted
  -1 -> all rows deleted, but this is the same as reload = -1

**Comment by maximilianweidenauer** [comment]
Instead of deletedRow, the server now sends changedValue, At first I implemented it, that changedValues just overwrites the data in the storage, but there was still flickering, because the components built themselves faster than the dpchanged response could change the data. So instead in the responses I moved the dpchanged response before the screen.generic response so the data is already up to date.
