### ISSUE TITLE
Restart not possible

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#240]
Application shows: Error occured

The problem is that the hostname is not available (switche network).
But the exception in console is not good.

The request:
Fetch failed loading: POST "http://jrmb.fritz.box:8080/services/mobile/api/deviceStatus".

Why?

```
Server.ts:161  Uncaught (in promise) TypeError: Failed to fetch
    at Server.ts:161
    at new Promise (<anonymous>)
    at e.value (Server.ts:156)
    at Object.retry (Server.ts:191)
    at onClick (ErrorDialog.tsx:63)
    at Object.qt (react-dom.production.min.js:52)
    at Gt (react-dom.production.min.js:52)
    at react-dom.production.min.js:53
    at Tr (react-dom.production.min.js:100)
    at Pr (react-dom.production.min.js:101)
```

**Comment by maximilianweidenauer** [comment]
The problem was that I once implemented a "reject(error)" to display the error message in the errorbar better, this didn't work as planned and I left the code in... Now everytime a request failed to reach the server an unhandled rejection crashed the app... 

I don't need the rejection because the initial catch of the sendRequest function already logs the error. Any other catches would be duplicate logs
