### ISSUE TITLE
Primereact theming support

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#247]
Would be great to use primereact theming (https://www.primefaces.org/designer/api/primereact/7.1.0/) as base for our themes or a new theme which is based on a primereact theme, created with https://www.primefaces.org/designer-react/#/

We should check what's possible.

**Comment by maximilianweidenauer** [comment]
The designer doesn't support all of the desired possibilities.

So the plan is to use the designer to its maximum, then download the css file, the css file then has to be altered by a script or something like that, because the file will also include some styling rules which are going to override our own, we only want the variables. The user will have to complete the missing variables the designer doesn't support on their own.

I will look into that later though, because another bug is more important right now.
