### ISSUE TITLE
Accessibility support (Aria)

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#28]
Currently, we don't set aria tags. This is already solved in vaadin UI of JVx and we could copy the functionality.

**Comment by rjahn** [comment]
In our vaadin UI, we set different tags like:

aria-label
aria-pressed

Current server implementation doesn't send aria information, but it will.
Every editor will send a new property: ariaLabel
So if ariaLabel is available, set it as aria-label

ariaPressed 

will be also a new property for Choice Editors, Checkbox editors and Checkboxes, toggle buttons

**Comment by rjahn** [comment]
ariaLabel property for buttons as well

**Comment by rjahn** [comment]
current server supports ariaLabel, ariaPressed

But cellEditors don't send aria information!
It's important to set ariaPressed for Checkbox Cell Editors. Also for Choice CellEditors if there are only two values and the first value is selected.

**Comment by maximilianweidenauer** [comment]
Added labels/pressed for the components that receive those properties additional info:

- For a lot of components the aria-checked state (of PrimeReact) is on the actual element (like Checkbox) but the aria-label is on the wrapped span. I don't really know if this will be a problem we need to try it out
-  I had to wrap DateCellEditor , LinkedCellEditor and NumberCellEditor in an extra span because PrimeReact won't allow me to add aria-label to their component, this could be fixed in 7.0.0 https://github.com/primefaces/primereact/issues/839
- Is there aria stuff for tab-panel, table tree?

**Comment by maximilianweidenauer** [comment]
Try with a screenreader
