### ISSUE TITLE
Screen navigation

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#332]
If you use. e.g:

`http://localhost:8080/app/ui/DemoApp/?language=de#/Components`

or 

`http://localhost:8080/app/ui/DemoApp/?language=de#/home/Components`

the Components screen should open if possible? 

Currently, the initial navigation is ignored.

**Comment by maximilianweidenauer** [comment]
This works if the screen was already opened before, if the screen hasn't been opened before, I would have to know the navigationName before.

I handle it like this:
Screen opens -> I save the navigationName as key with the openScreen componentId as value -> then when the URL changes. I'm looking if I've already got the navName in the map and open the screen if available.

So the problem is, that I would need the navigationName when the server sends the menu, which could be problematic because screens could have the same navigationName (if screens have the same navigationName, I add a number next to it eg.  First -> First1)

**Comment by maximilianweidenauer** [comment]
The tests i tried worked, but it definetly needs some more testing! Also I haven't tried welcome-screen

**Comment by rjahn** [comment]
Welcome screen is an important thing, because it's not unusual.
