### ISSUE TITLE
re-select table record

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#353]
Currently, if you click a row in a table, selectRecord is sent to server. If you try to click again, mouse event are used.

Questions: 

Why is the first click a selectRecord? Why is the second click different?
We should use the same command in both clicks -> selectRecord

But if there's a mouse/clicked/pressed listener... needs discussion.

**Comment by rjahn** [comment]
I guess in flutter UI it's always selectRecord?

**Comment by maximilianweidenauer** [comment]
The first click is selectRecord, because the selection most likely changed, I'm using the `onSelectionChanged` event. On the second click, when clicking the same column, `onSelectionChange` doesn't trigger because neither the row or column changed. I've just tried adding the events `onRowSelect` and `onRowClick` but both of them don't fire, they don't work with `selectionMode: cell` which I'm using

**Comment by maximilianweidenauer** [comment]
So we could just leave it like it is now, or I'll will have to add an additional mousepress to each row

**Comment by maximilianweidenauer** [comment]
There are mouse-events configured: `eventFocusGained
: 
true
eventMousePressed
: 
true
eventMouseReleased
: 
true`

**Comment by maximilianweidenauer** [comment]
I asked Martin about this issue and he said that it probably won't be a problem if I don't send selectRecord again

**Comment by maximilianweidenauer** [comment]
Now I'm using `onSelectionChanged` to create a helper variable and before the mouse-events I'm using this helper to always send the currently selectedRow to the server even if it was selected before.
