### ISSUE TITLE
Alive and Server unreachable problem

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#358]
Authenticated user (features)
Stop server -> wait for unreachable message
-> Start server after message appears

-> Session expired appears, but some seconds later -> unreachable again...

Looks like a timing problem?

We need more tests with stop/start server and alive.

**Comment by maximilianweidenauer** [comment]
So the issue is that the session expired message is overwritten by the unreachable text because the websocket is still trying to reconnect... Should I stop trying to reconnect when the session expires? Seems good to me because then the websocket can't connect anyways because it needs a new clientId to connect.

**Comment by rjahn** [comment]
session expired means that server is available but session can't be used. So it makes no sense to use the same session id again.
