### ISSUE TITLE
Invalid server version shows server not reachable

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#382]
If you get an invalid server version message (simply set 1.0.0), the message will be changed to: Server not reachable...

I guess this is not right.

Also: Please change the version message to the same as used in flutter

**Comment by maximilianweidenauer** [comment]
This was happening because at first the invalid server message error was set and later the server not reachable message was set...
Only SessionExpired error was not overwritable.
Now I've implemented a priority system, an error with a lower priority can't overwrite an error with a higher priority.

Referrence:
SessionExpired: 11,
Invalid Server Version: 10,
Server not reachable: 8,
Timeout: 7,
Startup failed: 6,
"Normal Error" which triggers the Errorbar: 5
Could not load translation: 5

Maybe Invalid Server Version higher prio than Session Expired, but the possibility that these two would overwrite each other should be 0 right?

**Comment by rjahn** [comment]
Right!

**Comment by rjahn** [comment]
If you get an invalid server version you don't get a session.
