### ISSUE TITLE
Upload without fileId

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#422]
It happened that the fileId is empty for uploads:

<img width="604" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/fd766df9-6a68-406f-8d1a-182dbb14ae9a">

I tried uploading different images with different sizes and a slow internet connection.

A pressButton command returned the fileId:

<img width="1108" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/29dd79a9-69c7-4346-b0d8-651f4ef98df3">

**Comment by maximilianweidenauer** [comment]
did this happen via an "UploadButton"? We put in some extra logic, if the upload occurs by UploadButton,
The button in the Up-and Downloadscreen of the demo is not an UploadButton

**Comment by rjahn** [comment]
Yes, it's an UploadButton

**Comment by maximilianweidenauer** [comment]
Please test with newest commit

**Comment by maximilianweidenauer** [comment]
So the issue was:
When using an UploadButton, I always opened the File Picker programmatically, then when the user selects a file before the upload response (with the fileId) returns, reactUI uploaded a file without fileId.

How I was trying to solve it:
Instead of opening the dialog onClick, open it when the upload response is here --> this won't work because the dialog only opens when a real interaction happens (click). 

So now there are 2 ugly solutions:
1. (my solution): open the dialog and save the upload action. If the upload response is late check, if there is a saved upload when the response comes, immediately send the file.

2. (Martin's solution): When the upload response is late, open a dialog with another button, when that is clicked open the file picker and the upload can happen then

**Comment by maximilianweidenauer** [comment]
solution 2 is now implemented
