### ISSUE TITLE
Mouse click multiple times - sometimes

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#497]
Mouse screen

First click on second icon, opens a popup 2 times (see video)
After first click, everything looks fine.

It only occurs after screen was opened.

To reproduce, open another screen and then the Mouse screen again...

https://github.com/sibvisions/reactUI/assets/1307043/5da3f3f4-2f24-4078-a950-59f227189ef5

**Comment by gimmixAT** [comment]
This seems to be caused by a `api/changes` messages coming via the websocket. After that a changes query is sent to the server which responds again with the dialog sent by the click response before. This causes the dialog to be rerendered and the animation to run again.
I'll try to mitigate this on the react side but I am not sure if the `changes` request back and forth is actually intended.

**Comment by rjahn** [comment]
I guess there are some checks for duplicate messages.

If you open a message and e.g. resize the browser from mini to small, the client will receive the message again?
I will check why the server sends `api/changes`. Usually this is a special message for UI updates in case of thread usage.

**Comment by rjahn** [comment]
Clear: The `api/changes` happens in case of screen-close. 

The application closes a screen with a delay of 1 sec. in a specific thread. This thread sends `api/changes` if it's done.

A possible solution could be: queue the `changes` request, because it makes no sense to send a request while another request is processing?

And if you receive the same message again, there should be some logic already to check if the message is already open?
