### ISSUE TITLE
Proof API

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#67]
We should check that our API for screen customization is developer friendly. The example application https://github.com/sibvisions/reactUI.example/ can be used.

Use-case: A react developer tries to use the library and tries to extend an application.

It must be possible to do this with our API.

Simply implement all missing pieces and extend the example application.

**Comment by gimmixAT** [comment]
Some notes / thoughts on the current state of the API:
- specifiying the `menuGroup` just as the label string might be a bit limiting in the future. Configuring Menu Structure and Screens separately might be more flexible.
- Looking up the Widget / Screen IDs in VisionX might be somewhat tedious so if it makes sense we might want to create a list of constants with all the Ids.
- For custom screens I think it might be more convenient and reacty if you can add the default content via the children prop instead of a Component. Now you have to make sure to use the correct Component (WorkScreen vs. GlobalWorkscreen) depending on how you want to use the custom screen.
- combining the custom and replace screens into a single prop could make the api a bit simpler conceptually

**Comment by rjahn** [comment]
* screen ids are not fixed. In VisionX, if you press Option (MacOS) or Alt (all other OS), you can find out the id very easily.
* popups are a nice feature
