### ISSUE TITLE
Proof styling

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#69]
Custom application styling via scss

Use example application and test how it's possible to change colors, fonts, ....

It should be easy to create custom style files.

**Comment by gimmixAT** [comment]
I played around with this a little and styling with the current setup is quite nice.

Thanks to the use of css variables in all the components fonts & colors can be easily set on a custom screen level without having to write overrides for every widget.

One possible downside is that all custom styles are added without any namespacing so there might be conflicts between multiple custom screens. On the other hand this also a feature because you can easily write styles that manipulate things around the screen. As long as we make sure that devs are aware of this we don't need to "improve" this.

**Comment by rjahn** [comment]
We could add a style with prefix and one without. Has the advantage of global and per component style. We could override the global or the component style.
